#!/bin/bash
# List of all versions that don't recieve traffic, except last deployed version
previous_versions=$(gcloud app versions list --sort-by LAST_DEPLOYED | grep -v '1.00' | sed 1d | awk '{print $2}' | tr '\n' ' ');
# Loop with previous versions stopping
#for i in $(gcloud app versions list --sort-by LAST_DEPLOYED | grep -v '1.00' | sed 1d | awk '{print $2}');
#do
  #gcloud app versions stop --quiet --project ${{ secrets.GCP_PROJECT }} --service ${{ secrets.GCP_APP_SERVICE_NAME }} $i;
  echo "Stopped App Engine version - $previous_versions"
#done
